In [1]:
import numpy as np

1. Create a rank 2 (2D) array that resembles the matrix below.
[[11 12 13 14]
 [15 16 17 18]]

In [2]:
Array_2D = np.array([[11,12,13,14],[15,16,17,18]])
print(Array_2D)

[[11 12 13 14]
 [15 16 17 18]]


1. Create an array with 4 rows and 3 columns of zeros. Your results should look as below:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

In [3]:
array0 = np.zeros((4, 3))
print(array0)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


2.Create an array of ones that has 3 rows and 4 columns. Your results should look as below:
[[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]]

In [4]:
array1 = np.ones((3,4))
print(array1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


3. Create an array containing integers 4 to 13 inclusive. Your results should look as below:
[4 5 6 7 8 9 10 11 12 13]

In [5]:
array_3 = np.array(range(4, 14))
print(array_3)

[ 4  5  6  7  8  9 10 11 12 13]


4. Create an array containing
[0., 1.5, 3., 4.5]

In [6]:
my_array = np.array([0.0, 1.5, 3.0, 4.5])
print(my_array)

[0.  1.5 3.  4.5]


5. Create a 2 by 2 array containing '4' in each position. Your results should look like this:
[[4 4]
 [4 4]]

In [7]:
my_array = np.full((2, 2), 4)
print(my_array)

[[4 4]
 [4 4]]


6
. Create 2 matrices:
i. Identity matrix of size 4
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
ii. Diagonal matrix with [10,12] as the diagonals
[[10  0]
 [ 0 12]]

In [8]:
my_array = np.eye(4)
print(my_array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
my_array = np.diag([10,12])
print(my_array)

[[10  0]
 [ 0 12]]


7. Create a 3 by 3 array with random floats in [0, 10]. Your answer may be different because it is random but it should look something like this:
[[6.3685612  0.61720883 8.93157783]
 [3.69927617 5.79879583 7.62145626]
 [7.21895112 4.02011535 4.48844787]]

In [10]:
my_array = np.random.rand(3,3)*10
print(my_array)

[[6.8511993  5.55543875 0.78495692]
 [1.26340545 2.39666647 0.71309932]
 [0.17381146 5.95358377 5.73636949]]


8. Create a 3 by 3 array with random integers in [10, 20]. Your answer may be different because it is random but it should look something like this:
[[19 11 13]
 [10 11 13]
 [11 14 10]]


In [11]:
my_array = np.random.randint(10, 21, size=(3, 3))
print(my_array)

[[10 18 18]
 [12 17 18]
 [11 18 10]]


1. Use this array for the following practice:
myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])
a. Get a subarray of the first row and first 2 columns. Your results should look like this:
[11 12]
b. Change all elements in 1st and second row to 0. Your results should look like this:
[[ 0  0  0]
 [ 0  0  0]
 [17 18 19]]

In [12]:
myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])
#a
array_a = myArray[0, :2]
print(array_a)

#b
myArray[:2, :] = 0
print(myArray)



[11 12]
[[ 0  0  0]
 [ 0  0  0]
 [17 18 19]]


2. Create an array that contains [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20] and reverse the order.

In [13]:
original_array = np.arange(21)  # Creates an array from 0 to 20
reversed_array = original_array[::-1]  # Reverses the order of the array
print(reversed_array)

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


Use this array for the following practice:
myArray = np.array([[11,12,13], [14,15,16]])
Reshape the array to an array with 3 rows. Your results should look like this:
[[11 12]
 [13 14]
 [15 16]]

In [14]:
myArray = np.array([[11,12,13], [14,15,16]])

new_array = myArray.reshape(3, -1)
print(new_array)


[[11 12]
 [13 14]
 [15 16]]


Use this array for the following practice:
myArray = np.arange(10)
1. Find the square of every number in array
2. Find the square root of every number in array
3. Multiply the square of each number in array with its respective square root

In [15]:
myArray = np.arange(10)

# 1.
squared_array = np.square(myArray)

# 2. 
sqrt_array = np.sqrt(myArray)

# 3.
result_array = squared_array * sqrt_array

print("Squared array:", squared_array)
print("Square root array:", sqrt_array)
print("Result array:", result_array)

Squared array: [ 0  1  4  9 16 25 36 49 64 81]
Square root array: [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
Result array: [  0.           1.           5.65685425  15.58845727  32.
  55.90169944  88.18163074 129.64181424 181.01933598 243.        ]


ADDING ELEMENTS
Use this array for the following practice:
myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])
1. Add a new row of elements containing 20, 21 and 22
2. Add a new column of elements containing 30, 40 and 50

INSERTING ELEMENTS
1. Add 1 column of 1 to this array: myArray = np.zeros((2,2))
2. Add 2 rows of 2 to the answer from part 1
3. Remove the last column
4. Remove the last row

In [16]:
myArray = np.zeros((2, 2))
myArray = np.insert(myArray, 2, 1, axis=1)

# 2. Add 2 rows of 2 to the answer from part 1
myArray = np.insert(myArray, 2, 2, axis=0)
myArray = np.insert(myArray, 2, 2, axis=0)

# 3. Remove the last column
myArray = np.delete(myArray, -1, axis=1)

# 4. Remove the last row
myArray = np.delete(myArray, -1, axis=0)

print(myArray)

[[0. 0.]
 [0. 0.]
 [2. 2.]]


DELETING ELEMENTS
Remove the elements from the middle column of this array:
myArray = np.matrix([[1, 2, 3], [4, 5, 6], [9, 8, 7]])
Your codes should look like this:
[[1 3]
 [4 6]
 [9 7]]

In [17]:
myArray = np.matrix([[1, 2, 3], [4, 5, 6], [9, 8, 7]])

# Remove the middle column (column index 1)
result_array = np.delete(myArray, 1, axis=1)

print(result_array)


[[1 3]
 [4 6]
 [9 7]]


Replace all odd numbers in the given array with -1
Start with:
exercise_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Desired output:
[ 0, -1, 2, -1, 4, -1, 6, -1, 8, -1]

In [18]:
MY_array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Find indices of odd numbers
odd_indices = np.where(MY_array1 % 2 != 0)

# Replace odd numbers with -1
MY_array1[odd_indices] = -1

print(MY_array1)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Convert a 1-D array into a 2-D array with 3 rows
Start with:
exercise_2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
Desired output:
[[ 0, 1, 2]
[3, 4, 5]
[6, 7, 8]]

In [19]:
exercise_2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
result = exercise_2.reshape(3, -1)

print(result)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Add 202 to all the values in given array
Start with:
exercise_3 = np.arange(4).reshape(2,-1)
Desired output:
[[202, 203]
[204, 205]]


In [20]:
exercise_3 = np.arange(4).reshape(2,-1)
result = exercise_3 + 202

print(result)

[[202 203]
 [204 205]]


Generate a 1-D array of 10 random integers. Each integer should be a number between 30 and 40 (inclusive)
Sample of desired output:
[36, 30, 36, 38, 31, 35, 36, 30, 32, 34]

In [21]:
random_integers = np.random.randint(30, 41, size=10)
print(random_integers)

[32 36 36 31 34 34 38 34 30 31]


Find the positions of:
elements in x where its value is more than its corresponding element in y, and
elements in x where its value is equals to its corresponding element in y.
Start with these:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
Desired output:
(array([1, 2, 4, 5, 6, 7, 8, 9]),) and (array([0]),)

In [22]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

greater_than_y = np.where(x > y)[0]
equal_to_y = np.where(x == y)[0]

print(greater_than_y, equal_to_y)

[1 2 4 5 6 7 8 9] [0]


Extract the first four columns of this 2-D array
Start with this:
exercise_6 = np.arange(100).reshape(5,-1)
Desired output:
[[ 0 1 2 3]
[20 21 22 23]
[40 41 42 43]
[60 61 62 63]
[80 81 82 83]]

In [23]:
exercise_6 = np.arange(100).reshape(5,-1)
first_four_columns = exercise_6[:, :4]

print(first_four_columns)

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]
